CREATE DATABASE BOOTCAMP_EXERCISE1;
USE BOOTCAMP_EXERCISE1;
CREATE TABLE job_grades (
	GRADE_LEVEL VARCHAR(2) PRIMARY KEY,
    LOWEST_SAL DECIMAL(5,2) ,
    HIGHEST_SAL DECIMAL(5,2)
);
CREATE TABLE regions (
	REGION_ID INT PRIMARY KEY,
    REGION_NAME VARCHAR(25) 
);
CREATE TABLE jobs (
	JOB_ID VARCHAR(10) PRIMARY KEY,
    JOB_TITLE VARCHAR(25),
    MIN_SALARY DECIMAL(5,2),
    MAX_SALARY DECIMAL(5,2)
);
CREATE TABLE countries (
	COUNTRY_ID CHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(40) ,
    REGION_ID INT ,
    FOREIGN KEY (REGION_ID) REFERENCES regions(REGION_ID)
);
CREATE TABLE locations (
	LOCATION_ID INT PRIMARY KEY,
    STREET_ADDRESS VARCHAR(25),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(12),
    COUNTRY_ID CHAR(2) ,
    FOREIGN KEY (COUNTRY_ID) REFERENCES countries(COUNTRY_ID)
);
CREATE TABLE departments (
	DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30) ,
    MANAGER_ID INT ,
    LOCATION_ID INT,
    FOREIGN KEY (LOCATION_ID) REFERENCES locations(LOCATION_ID)
) ;
CREATE TABLE employees (
	EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25),
    EMAIL VARCHAR(25),
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE,
    JOB_ID  VARCHAR(10),
    FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID),
    SALARY DECIMAL(5,2),
    COMMISSION_PCT DECIMAL(5,2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT ,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID)
);
CREATE TABLE job_history(
	EMPLOYEE_ID INT,
    START_DATE DATE,
    PRIMARY KEY (EMPLOYEE_ID, START_DATE),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES employees(EMPLOYEE_ID),
    END_DATE DATE,
    JOB_ID VARCHAR(10),
    FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID),
    DEPARTMENT_ID INT ,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID) 
);

